title: "MK Epidemiologi dan Ekonomi Veteriner"
description: "Program Studi Kedokteran Hewan, Fakultas Kedokteran, Universitas Hasanuddin"
url: "https://username.github.io"        # ganti dengan username GitHub Rian
baseurl: "/epidemiologi-dan-ekonomi-veteriner"                    # ganti dengan nama repo yang sebenarnya
markdown: kramdown
theme: null
